USE [Easyhelp]
GO

INSERT INTO Airlines (AirlineName, IsEligibleForClaim) 
VALUES
           ('Aer Lingus', 1),
		   ('Aeroflot', 1), 
		   ('Aeroflot Russian Airlines', 1),
		   ('Aerolineas Argentinas', 1),
		   ('Aeromexico', 1),
		   ('Afriqiyah Airways', 1),
		   ('Aigle Azur', 1),
		   ('Air Algerie', 1),
		   ('Air Alps', 1),
		   ('Air Armenia', 1),
		   ('Air Atlanta Icelandic', 1),
		   ('Air Austral', 1),
		   ('Air Cairo', 1),
		   ('Air Canada', 1),
		   ('Air China', 1),
		   ('Air Comet', 1),
		   ('Air Dolomiti', 1),
		   ('Air Europa', 1),
		   ('Air Finland', 1),
		   ('Air France', 1),
		   ('Air Greenland', 1),
		   ('Air India', 1),
		   ('Air Italy', 1),
		   ('Air Madagascar', 1),
		   ('Air Malta', 1),
		   ('Air Mauritius', 1),
		   ('Air Mediterranee', 1),
		   ('Air Memphis', 1),
		   ('Air Moldov', 1),
		   ('Air New Zealand', 1),
		   ('Air Nostrum', 1),
		   ('Air One', 1),
		   ('Air Senegal International', 1),
		   ('Air Seychelles', 1),
		   ('Air Slovakia', 1),
		   ('Air Transat', 1),
		   ('AirVallee', 1),
		   ('airBaltic', 1),
		   ('airberlin', 1),
		   ('Airlinair', 1),
		   ('Albanian Airlines', 1),
		   ('Alidaunia', 1),
		   ('Alitalia', 1),
		   ('Alitalia Express', 1),
		   ('AMC Airlines', 1),
		   ('American Airlines', 1),
		   ('ANA – All Nippon Airways', 1),
		   ('Arkefly', 1),
		   ('Arkia', 1),
		   ('Armavia', 1),
		   ('Astraeus', 1),
		   ('Atlantic Airways (Faroe Islands)', 1),
		   ('Atlas Blue', 1),
		   ('Atlasjet Airlines', 1),
		   ('Aurela', 1),
		   ('Aurigny Air Services', 1),
		   ('Austrian', 1),
		   ('Avianca', 1),
		   ('AVIES Air Company', 1),
		   ('Azerbaijan Airlines', 1),
		   ('B H Air', 1),
		   ('Baltic Airline', 1),
		   ('Baboo', 1),
		   ('Belair Airlines', 1),
		   ('Belavia', 1),
		   ('Biman Bangladesh Airlines', 1),
		   ('Binter Canarias', 1),
		   ('Blue 1', 1),
		   ('Blue Air', 1),
		   ('Blue Line', 1),
		   ('Blue Panorama Airlines', 1),
		   ('Blue Wing Airlines', 1),
		   ('bmi', 1),
		   ('bmibaby', 1),
		   ('British Airways', 1),
		   ('Brussels Airlines', 1),
		   ('Bulgaria Air', 1),
		   ('Bulgarian Air Charter', 1),
		   ('Carpatair', 1),
		   ('Cathay Pacific', 1),
		   ('CCM Airlines', 1),
		   ('Central Connect Airlines', 1),
		   ('China Airlines', 1),
		   ('Cimber Air', 1),
		   ('Cirrus Airlines', 1),
		   ('City Airline', 1),
		   ('Clickair', 1),
		   ('Compagnie Aérienne du Mali', 1),
		   ('Condor Flugdienst', 1),
		   ('Continental Airlines', 1),
		   ('Corsairfly', 1),
		   ('Croatia Airlines', 1),
		   ('CSA Czech Airlines', 1),
		   ('Cubana', 1),
		   ('Cyprus Airways', 1),
		   ('Danu Oro Transportas', 1),
		   ('Darwin Airline', 1),
		   ('DAT- Danish Air Transport', 1),
		   ('DeltaAirlines', 1),
		   ('Dniproavia', 1),
		   ('Donbassaero', 1),
		   ('Dubrovnik Airline', 1),
		   ('Eastern Airways', 1),
		   ('EasyJet', 1),
		   ('EasyJet Switzerland', 1),
		   ('Edelweiss Air', 1),
		   ('Egyptair', 1),
		   ('El Al', 1),
		   ('Emirates Airline', 1),
		   ('Eritrean Airlines', 1),
		   ('Estonian Air', 1),
		   ('Ethiopian Airlines', 1),
		   ('Etihad Airways', 1),
		   ('Euroair', 1),
		   ('Eurocypria Airlines', 1),
		   ('Eurofly', 1),
		   ('Europe Airpost', 1),
		   ('European Aircharter', 1),
		   ('Eurowings', 1),
		   ('EVA Air', 1),
		   ('Finnair', 1),
		   ('FinnComm Airlines', 1),
		   ('First Choice Airways', 1),
		   ('Flightline', 1),
		   ('Flybe', 1),
		   ('flyglobespan', 1),
		   ('flyLAL', 1),
		   ('Freebird Airlines', 1),
		   ('GB Airways', 1),
		   ('Georgian Airways', 1),
		   ('Germanwings', 1),
		   ('Gir Jet', 1),
		   ('Golden Air', 1),
		   ('Gulf Air', 1),
		   ('Hahn Air', 1),
		   ('Hamburg International', 1),
		   ('Hello', 1),
		   ('Helvetic Airways', 1),
		   ('Hemus Air', 1),
		   ('Hex’ Air', 1),
		   ('Hola Airlines', 1),
		   ('IBA International Business Air', 1),
		   ('Iberia', 1),
		   ('Iberworld', 1),
		   ('Icelandair', 1),
		   ('InterSky', 1),
		   ('Interstate Airlines', 1),
		   ('Iran Air', 1),
		   ('Islas Airways', 1),
		   ('Iraq Airlines', 1),
		   ('Israir', 1),
		   ('ItAli Airlines', 1),
		   ('Izair', 1),
		   ('Japan Airlines International', 1),
		   ('JAT Airways', 1),
		   ('Jet Air (Poland)', 1),
		   ('Jet Airways', 1),
		   ('Jet Time', 1),
		   ('Jet2', 1),
		   ('Jet4You', 1),
		   ('JetAir Fly', 1),
		   ('JetX', 1),
		   ('Karthago Airlines', 1),
		   ('KD-Avia', 1),
		   ('KLM cityhopper', 1),
		   ('KLM Royal Dutch Airlines', 1),
		   ('KMV – Kavkazskie Mineralnye Vody', 1),
		   ('Korean Air', 1),
		   ('Kuban Airlines', 1),
		   ('Kuwait Airways', 1),
		   ('LAN Airlines', 1),
		   ('LAN Ecuador', 1),
		   ('LAN Peru', 1),
		   ('Libyan Airlines', 1),
		   ('Livingston Energy Flight', 1),
		   ('Lloyd Aereo Boliviano', 1),
		   ('LOT- Polish Airlines', 1),
		   ('Lotus Air', 1),
		   ('LTU', 1),
		   ('Lufthansa', 1),
		   ('Lufthansa CityLine', 1),
		   ('Luxair – Luxembourg Airlines', 1),
		   ('Malaysia Airlines', 1),
		   ('MALEV Hungarian Airlines', 1),
		   ('Malmo Aviation', 1),
		   ('Martinair', 1),
		   ('MAT – Macedonian Airlines', 1),
		   ('Meridiana', 1),
		   ('Middle East Airlines', 1),
		   ('Mistral Air', 1),
		   ('MNG Airlines', 1),
		   ('Moldavian Airlines', 1),
		   ('Monarch Airlines', 1),
		   ('Montenegro Airlines', 1),
		   ('MyAir', 1),
		   ('MyTravel Airways', 1),
		   ('NAYSA', 1),
		   ('NEOS', 1),
		   ('NEX Time Jet AB', 1),
		   ('Niki', 1),
		   ('Nordic Airways', 1),
		   ('North flying', 1),
		   ('Northwest Airlines', 1),
		   ('Norwegian Air Shuttle', 1),
		   ('Norwegian.se', 1),
		   ('Nouvelair Tunisie', 1),
		   ('Novair', 1),
		   ('OLT – Ostfriesische Lufttransport', 1),
		   ('Olympic Airlines', 1),
		   ('Onur Air', 1),
		   ('Pakistan International Airlines', 1),
		   ('Pegasus Airlines', 1),
		   ('PGA – Portugalia Airlines', 1),
		   ('Philippine Airlines', 1),
		   ('PLUNA', 1),
		   ('Private Wings Flugcharter', 1),
		   ('Pullmantur Air', 1),
		   ('Qantas', 1),
		   ('Qatar Airways', 1),
		   ('Regional', 1),
		   ('Regional Air Lines', 1),
		   ('Romanian airlines', 1),
		   ('Rossiya – Russian Airlines', 1),
		   ('Royal Air Maroc', 1),
		   ('Royal Jordanian', 1),
		   ('Ryanair', 1),
		   ('S7 Airlines', 1),
		   ('Saravia', 1),
		   ('SAS', 1),
		   ('SATA Air Acores', 1),
		   ('SATA International', 1),
		   ('Saudi Arabian Airlines', 1),
		   ('ScotAirways', 1),
		   ('SevenAir', 1),
		   ('Severstal Aircompany', 1),
		   ('Singapore Airlines', 1),
		   ('Sky Airlines', 1),
		   ('Sky Express Airlines', 1),
		   ('Skyways Express', 1),
		   ('Smartlynx Airlines', 1),
		   ('South African Airways', 1),
		   ('South Airlines', 1),
		   ('Spanair', 1),
		   ('Sun D’Or International Airlines', 1),
		   ('Sun-Air of Scandinavia', 1),
		   ('SunExpress', 1),
		   ('Surinam Airways', 1),
		   ('Swiftair', 1),
		   ('Swissair', 1),
		   ('Syrianair', 1),
		   ('TACV Cabo Verde Airlines', 1),
		   ('TAM Linhas Aereas', 1),
		   ('TAP Portugal', 1),
		   ('TAROM', 1),
		   ('Tatarstan Air', 1),
		   ('Thai Airways International', 1),
		   ('Thomas Cook Airlines', 1),
		   ('Thomas Cook Airlines Belgium', 1),
		   ('Thomas Cook Airlines Scandinavia', 1),
		   ('Thomson Airways', 1),
		   ('Titan Airways', 1),
		   ('TNT Airways', 1),
		   ('Transavia Airlines', 1),
		   ('Transavia France', 1),
		   ('Travel Service Airlines', 1),
		   ('Travel Service Hungary', 1),
		   ('TUIFly', 1),
		   ('TUIFly Nordic AB', 1),
		   ('Tunisair', 1),
		   ('Turkish Airlines (THY)', 1),
		   ('Turkmenistan Airlines', 1),
		   ('Twin Jet', 1),
		   ('Ukraine International Airlines', 1),
		   ('UM Air', 1),
		   ('United Airlines', 1),
		   ('Ural Airlines', 1),
		   ('US Airways', 1),
		   ('UTAir', 1),
		   ('Uzbekistan Airways', 1),
		   ('VARIG – VRG Linhas Aereas', 1),
		   ('Varig Log', 1),
		   ('VIA – Air VIA', 1),
		   ('Viking Airlines', 1),
		   ('VIM Airlines', 1),
		   ('VLM Airlines', 1),
		   ('Virgin Atlantic Airlines', 1),
		   ('Volare S.p.A.', 1),
		   ('Vueling Airlines', 1),
		   ('Welcome Air', 1),
		   ('Wideroe', 1),
		   ('Wind Jet', 1),
		   ('Wizz Air', 1),
		   ('World Airways', 1),
		   ('XL Airways France', 1),
		   ('XL Airways Germany', 1),
		   ('Yemenia',1)